# Generated by Django 4.2 on 2023-04-10 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cases",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("case_type", models.CharField(max_length=20)),
                ("start_date", models.DateField(null=True)),
                ("demandante", models.CharField(max_length=30)),
                ("demandado", models.CharField(max_length=30)),
                ("juzgado", models.CharField(max_length=100)),
                ("partido_judicial", models.CharField(max_length=30)),
                ("phase", models.CharField(max_length=30)),
                ("cont_lawyer_one", models.CharField(max_length=30)),
                ("cont_lawyer_two", models.CharField(blank=True, max_length=30)),
                ("cont_lawyer_three", models.CharField(blank=True, max_length=30)),
                ("procurador_one", models.CharField(max_length=30)),
                ("procurador_two", models.CharField(blank=True, max_length=30)),
                ("procurador_three", models.CharField(blank=True, max_length=30)),
                ("pc_one", models.CharField(max_length=30)),
                ("pc_two", models.CharField(blank=True, max_length=30)),
                ("pc_three", models.CharField(blank=True, max_length=30)),
                ("lawyers", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Case",
                "verbose_name_plural": "Cases",
            },
        ),
        migrations.CreateModel(
            name="Documents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("doc", models.ImageField(upload_to="docs/")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "case_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="legalcases.cases",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CasePresentations",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("presentation_date", models.DateField(blank=True, null=True)),
                (
                    "case_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="legalcases.cases",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presentación",
                "verbose_name_plural": "Presentaciones",
            },
        ),
        migrations.CreateModel(
            name="CaseComments",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "case_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="legalcases.cases",
                    ),
                ),
            ],
            options={
                "verbose_name": "CaseComment",
                "verbose_name_plural": "CaseComments",
            },
        ),
    ]
